### ISSUE TITLE
Adequately space manual steps/instructions from automatic ones

### ISSUE THREAD

**Issue by jackVanish** [ocean-tracking-network/jb-acoustic-telemetry#1]
Jon and I, in discussing this workshop, mentioned that it might be worthwhile to teach both the manual way of loading/filtering data as well as the automatic way using our GLATOS libraries. I agree, but I'm wondering if we should put some space between the two, rather than teaching the automatic right after the manual. To my mind, this creates a little confusion, since they have to absorb two ways of doing things at once. 

I think we should section off as much of the automatic stuff as we can and teach it all at once, after we've taught all the manual steps and ensured that people have an understanding thereof. Thoughts and opinions from others?

**Comment by naomitress** [comment]
i would lean towards teaching the automatic method first. The manual way will be valuable for when people want to branch out and make changes to the code we are teaching, but having an end goal of a filtered, analyzed data set, the auto method will get us there faster.

**Comment by jackVanish** [comment]
@naomitress Is this another one that we've obsolesced?

**Comment by naomitress** [comment]
yes
